/* ===================================================================
   Billboard Hot 100 Data
   Year-End #1 songs (1946-2025) + Monthly #1 songs for key decades.
   1946-1957 yearly entries use Billboard's pre-Hot-100 retail-sales lists.
   YouTube video IDs included where available. null = use search link.
   =================================================================== */

const BILLBOARD = {

  /* -----------------------------------------------
     YEAR-END #1 SONGS
     ----------------------------------------------- */
  yearly: {
    1946: { title: "Prisoner of Love", artist: "Perry Como", ytId: "d7h_V5xd6Cc" },
    1947: { title: "Near You", artist: "Francis Craig", ytId: "hP5dg_g_tgM" },
    1948: { title: "Twelfth Street Rag", artist: "Pee Wee Hunt", ytId: "jrhT3ZB-vsI" },
    1949: { title: "Riders in the Sky", artist: "Vaughn Monroe", ytId: "etilXf4CPF0" },
    1950: { title: "Goodnight Irene", artist: "Gordon Jenkins and The Weavers", ytId: "saykpHOm5fc" },
    1951: { title: "Too Young", artist: "Nat King Cole", ytId: "KaFtsqU2V6U" },
    1952: { title: "Blue Tango", artist: "Leroy Anderson", ytId: "cGpPwQV9cxA" },
    1953: { title: "The Song from Moulin Rouge", artist: "Percy Faith", ytId: "LPDF2ORPOFQ" },
    1954: { title: "Little Things Mean a Lot", artist: "Kitty Kallen", ytId: "2C7SzKv2uLU" },
    1955: { title: "Cherry Pink and Apple Blossom White", artist: "Perez Prado", ytId: "pqk3F1pPjyA" },
    1956: { title: "Heartbreak Hotel", artist: "Elvis Presley", ytId: "e9BLw4W5KU8" },
    1957: { title: "All Shook Up", artist: "Elvis Presley", ytId: "23zLefwiii4" },
    1958: { title: "Volare (Nel Blu Dipinto Di Blu)", artist: "Domenico Modugno", ytId: "JqISNMosfgs" },
    1959: { title: "The Battle of New Orleans", artist: "Johnny Horton", ytId: "50_iRIcxsz0" },
    1960: { title: "Theme from A Summer Place", artist: "Percy Faith", ytId: "e0rWSbgbMOo" },
    1961: { title: "Tossin' and Turnin'", artist: "Bobby Lewis", ytId: "MmJLhVVz0IA" },
    1962: { title: "Stranger on the Shore", artist: "Mr. Acker Bilk", ytId: "S-Xm7s9eGxU" },
    1963: { title: "Sugar Shack", artist: "Jimmy Gilmer & The Fireballs", ytId: "sTjv4t4VnlQ" },
    1964: { title: "I Want to Hold Your Hand", artist: "The Beatles", ytId: "jenWdylTtzs" },
    1965: { title: "Wooly Bully", artist: "Sam the Sham & The Pharaohs", ytId: "KbT6qUpPv-A" },
    1966: { title: "The Ballad of the Green Berets", artist: "SSgt Barry Sadler", ytId: "m5WJJGSE_zA" },
    1967: { title: "To Sir, with Love", artist: "Lulu", ytId: "ELBHh-W-WVE" },
    1968: { title: "Hey Jude", artist: "The Beatles", ytId: "A_MjCqQoLLA" },
    1969: { title: "Sugar, Sugar", artist: "The Archies", ytId: "h9nE2spOw_o" },
    1970: { title: "Bridge over Troubled Water", artist: "Simon & Garfunkel", ytId: "4G-YQA_bsOU" },
    1971: { title: "Joy to the World", artist: "Three Dog Night", ytId: "GFMr7GJFBwo" },
    1972: { title: "The First Time Ever I Saw Your Face", artist: "Roberta Flack", ytId: "GkLGA1VAmjg" },
    1973: { title: "Tie a Yellow Ribbon Round the Ole Oak Tree", artist: "Dawn ft. Tony Orlando", ytId: "Yhi4kkjB5z4" },
    1974: { title: "The Way We Were", artist: "Barbra Streisand", ytId: "yHSYY5m5Lj0" },
    1975: { title: "Love Will Keep Us Together", artist: "Captain & Tennille", ytId: "RBCaUmMaJYI" },
    1976: { title: "Silly Love Songs", artist: "Wings", ytId: "ap87QgZKE80" },
    1977: { title: "You Light Up My Life", artist: "Debby Boone", ytId: "I3CjVfbjq4c" },
    1978: { title: "Shadow Dancing", artist: "Andy Gibb", ytId: "yPEyJtwLns8" },
    1979: { title: "My Sharona", artist: "The Knack", ytId: "bbr60I0u2Ng" },
    1980: { title: "Call Me", artist: "Blondie", ytId: "StKVS0eI85I" },
    1981: { title: "Bette Davis Eyes", artist: "Kim Carnes", ytId: "EPOIS5taqA8" },
    1982: { title: "Physical", artist: "Olivia Newton-John", ytId: "vWz9VN40nCA" },
    1983: { title: "Every Breath You Take", artist: "The Police", ytId: "OMOGaugKpzs" },
    1984: { title: "When Doves Cry", artist: "Prince", ytId: "UG3VcCAlUgE" },
    1985: { title: "Careless Whisper", artist: "Wham! ft. George Michael", ytId: "izGwDsrQ1eQ" },
    1986: { title: "That's What Friends Are For", artist: "Dionne & Friends", ytId: "HyTpu6BmE88" },
    1987: { title: "Walk Like an Egyptian", artist: "The Bangles", ytId: "Cv6tuzHUuuk" },
    1988: { title: "Faith", artist: "George Michael", ytId: "lu3VTngm1F0" },
    1989: { title: "Look Away", artist: "Chicago", ytId: "tbIEwIwYz-c" },
    1990: { title: "Hold On", artist: "Wilson Phillips", ytId: "uIbXvaE39wM" },
    1991: { title: "(Everything I Do) I Do It for You", artist: "Bryan Adams", ytId: "Y0pdQU87dc8" },
    1992: { title: "End of the Road", artist: "Boyz II Men", ytId: "zDKO6XYXioc" },
    1993: { title: "I Will Always Love You", artist: "Whitney Houston", ytId: "3JWTaaS7LdU" },
    1994: { title: "The Sign", artist: "Ace of Base", ytId: "iqu132vTl5Y" },
    1995: { title: "Gangsta's Paradise", artist: "Coolio ft. L.V.", ytId: "fPO76Jlnz6c" },
    1996: { title: "Macarena (Bayside Boys Mix)", artist: "Los Del Rio", ytId: "zWaymcVmJ-A" },
    1997: { title: "Candle in the Wind 1997", artist: "Elton John", ytId: "RbhcREeSRag" },
    1998: { title: "Too Close", artist: "Next", ytId: "kwse08s4gpc" },
    1999: { title: "Believe", artist: "Cher", ytId: "nZXRV4MsEfc" },
    2000: { title: "Breathe", artist: "Faith Hill", ytId: "gDSbrGBIhVs" },
    2001: { title: "Hanging by a Moment", artist: "Lifehouse", ytId: "tPnK39ax_AM" },
    2002: { title: "How You Remind Me", artist: "Nickelback", ytId: "1cQh1ccqu8M" },
    2003: { title: "In Da Club", artist: "50 Cent", ytId: "5qm8PH4xAss" },
    2004: { title: "Yeah!", artist: "Usher ft. Lil Jon & Ludacris", ytId: "GxBSyx85Kp8" },
    2005: { title: "We Belong Together", artist: "Mariah Carey", ytId: "0habxsuXW4g" },
    2006: { title: "Bad Day", artist: "Daniel Powter", ytId: "gH476CxJxfg" },
    2007: { title: "Irreplaceable", artist: "Beyoncé", ytId: "2EwViQxSJJQ" },
    2008: { title: "Low", artist: "Flo Rida ft. T-Pain", ytId: "wx6_MWVHZ4g" },
    2009: { title: "Boom Boom Pow", artist: "The Black Eyed Peas", ytId: "4m48GqaOz90" },
    2010: { title: "TiK ToK", artist: "Kesha", ytId: "iP6XpLQM2Cs" },
    2011: { title: "Rolling in the Deep", artist: "Adele", ytId: "rYEDA3JcQqw" },
    2012: { title: "Somebody That I Used to Know", artist: "Gotye ft. Kimbra", ytId: "8UVNT4wvIGY" },
    2013: { title: "Thrift Shop", artist: "Macklemore & Ryan Lewis", ytId: "QK8mJJJvaes" },
    2014: { title: "Happy", artist: "Pharrell Williams", ytId: "y6Sxv-sUYtM" },
    2015: { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", ytId: "OPf0YbXqDm0" },
    2016: { title: "Love Yourself", artist: "Justin Bieber", ytId: "oyEuk8j8imI" },
    2017: { title: "Shape of You", artist: "Ed Sheeran", ytId: "JGwWNGJdvx8" },
    2018: { title: "God's Plan", artist: "Drake", ytId: "xpVfcZ0ZcFM" },
    2019: { title: "Old Town Road", artist: "Lil Nas X ft. Billy Ray Cyrus", ytId: "w2Ov5jzm3j8" },
    2020: { title: "Blinding Lights", artist: "The Weeknd", ytId: "4NRXx6U8ABQ" },
    2021: { title: "Levitating", artist: "Dua Lipa", ytId: "TUVcZfQe-Kw" },
    2022: { title: "As It Was", artist: "Harry Styles", ytId: "H5v3kku4y6Q" },
    2023: { title: "Last Night", artist: "Morgan Wallen", ytId: "r7GDKeMeDqE" },
    2024: { title: "Lose Control", artist: "Teddy Swims", ytId: "GZ3zL7kT6_c" },
    2025: { title: "Die with a Smile", artist: "Lady Gaga & Bruno Mars", ytId: "kPa7bsKwL-c" }
  },

  /* -----------------------------------------------
     MONTHLY #1 SONGS (key by "YYYY-MM")
     Approximate Billboard Hot 100 #1 for each month.
     ----------------------------------------------- */
  monthly: {
    // ---- 1958 ----
    "1958-08": { title: "Volare (Nel Blu Dipinto Di Blu)", artist: "Domenico Modugno", ytId: "6jWsIpAbo-8" },
    "1958-09": { title: "Volare (Nel Blu Dipinto Di Blu)", artist: "Domenico Modugno", ytId: "6jWsIpAbo-8" },
    "1958-10": { title: "It's All in the Game", artist: "Tommy Edwards", ytId: "ubsb25Ckkbg" },
    "1958-11": { title: "Tom Dooley", artist: "The Kingston Trio", ytId: "nGGGQVGLTQ0" },
    "1958-12": { title: "The Chipmunk Song (Christmas Don't Be Late)", artist: "The Chipmunks with David Seville", ytId: "np2ZapISRzM" },

    // ---- 1960 ----
    "1960-01": { title: "Running Bear", artist: "Johnny Preston", ytId: "E3meEmDpaDU" },
    "1960-02": { title: "Theme from A Summer Place", artist: "Percy Faith", ytId: "fRV0yHiEua8" },
    "1960-03": { title: "Theme from A Summer Place", artist: "Percy Faith", ytId: "fRV0yHiEua8" },
    "1960-04": { title: "Stuck on You", artist: "Elvis Presley", ytId: "jVqR2PwX428" },
    "1960-05": { title: "Cathy's Clown", artist: "The Everly Brothers", ytId: "WvjuQaEBUoo" },
    "1960-06": { title: "Everybody's Somebody's Fool", artist: "Connie Francis", ytId: "GT0xaJllZws" },
    "1960-07": { title: "I'm Sorry", artist: "Brenda Lee", ytId: "6MHbyZn14LM" },
    "1960-08": { title: "It's Now or Never", artist: "Elvis Presley", ytId: "Uwelrtb8Oho" },
    "1960-09": { title: "My Heart Has a Mind of Its Own", artist: "Connie Francis", ytId: "RaMQq9w57GU" },
    "1960-10": { title: "Save the Last Dance for Me", artist: "The Drifters", ytId: "BmTmF6neTTg" },
    "1960-11": { title: "Are You Lonesome Tonight?", artist: "Elvis Presley", ytId: "9XVdtX7uSnk" },
    "1960-12": { title: "Are You Lonesome Tonight?", artist: "Elvis Presley", ytId: "9XVdtX7uSnk" },

    // ---- 1965 ----
    "1965-01": { title: "I Feel Fine", artist: "The Beatles", ytId: "WrAV5EVI4tU" },
    "1965-02": { title: "You've Lost That Lovin' Feelin'", artist: "The Righteous Brothers", ytId: "xbg1gkWb0Wo" },
    "1965-03": { title: "Eight Days a Week", artist: "The Beatles", ytId: "XTfmuDjwQTw" },
    "1965-04": { title: "I'm Telling You Now", artist: "Freddie and the Dreamers", ytId: "ALR13MJLAs4" },
    "1965-05": { title: "Mrs. Brown, You've Got a Lovely Daughter", artist: "Herman's Hermits", ytId: "HSWisXwv_sI" },
    "1965-06": { title: "I Can't Help Myself (Sugar Pie Honey Bunch)", artist: "Four Tops", ytId: "s3bksUSPB4c" },
    "1965-07": { title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", ytId: "MSSxnv1_J2g" },
    "1965-08": { title: "I Got You Babe", artist: "Sonny & Cher", ytId: "HKGjCPBSG38" },
    "1965-09": { title: "Help!", artist: "The Beatles", ytId: "N4KvafPbauw" },
    "1965-10": { title: "Yesterday", artist: "The Beatles", ytId: "NrgmdOz227I" },
    "1965-11": { title: "Get Off of My Cloud", artist: "The Rolling Stones", ytId: "1sWqmMAvmdU" },
    "1965-12": { title: "Turn! Turn! Turn!", artist: "The Byrds", ytId: "xVOJla2vYx8" },

    // ---- 1970 ----
    "1970-01": { title: "Raindrops Keep Fallin' on My Head", artist: "B. J. Thomas", ytId: "sySlY1XKlhM" },
    "1970-02": { title: "Bridge over Troubled Water", artist: "Simon & Garfunkel", ytId: "4G-YQA_bsOU" },
    "1970-03": { title: "Bridge over Troubled Water", artist: "Simon & Garfunkel", ytId: "4G-YQA_bsOU" },
    "1970-04": { title: "ABC", artist: "The Jackson 5", ytId: "ISqzbbZVIiU" },
    "1970-05": { title: "American Woman / No Sugar Tonight", artist: "The Guess Who", ytId: "9uf6EY2BZBw" },
    "1970-06": { title: "The Love You Save", artist: "The Jackson 5", ytId: "AU3geksaNAw" },
    "1970-07": { title: "(They Long to Be) Close to You", artist: "The Carpenters", ytId: "6yUq_-_v4rI" },
    "1970-08": { title: "War", artist: "Edwin Starr", ytId: "hZJRJpbGkG4" },
    "1970-09": { title: "Ain't No Mountain High Enough", artist: "Diana Ross", ytId: "EjCz_sUVZ5U" },
    "1970-10": { title: "I'll Be There", artist: "The Jackson 5", ytId: "PmeLxaBNrAI" },
    "1970-11": { title: "I Think I Love You", artist: "The Partridge Family", ytId: "bb4FMn-IWEY" },
    "1970-12": { title: "My Sweet Lord / Isn't It a Pity", artist: "George Harrison", ytId: "-n-LULDiJxk" },

    // ---- 1975 ----
    "1975-01": { title: "Mandy", artist: "Barry Manilow", ytId: "AvGpvQbkccE" },
    "1975-02": { title: "Pick Up the Pieces", artist: "Average White Band", ytId: "CFOOtzQhGmk" },
    "1975-03": { title: "My Eyes Adored You", artist: "Frankie Valli", ytId: "vYtpKBNTCB8" },
    "1975-04": { title: "Philadelphia Freedom", artist: "Elton John Band", ytId: "sOF6_kHBkyg" },
    "1975-05": { title: "He Don't Love You (Like I Love You)", artist: "Tony Orlando and Dawn", ytId: "vC9Ogt0AExM" },
    "1975-06": { title: "Love Will Keep Us Together", artist: "Captain & Tennille", ytId: "GpBZNh70uhA" },
    "1975-07": { title: "The Hustle", artist: "Van McCoy and the Soul City Symphony", ytId: "4fBQHzMumlo" },
    "1975-08": { title: "Jive Talkin'", artist: "Bee Gees", ytId: "LHMm5JZzooY" },
    "1975-09": { title: "Fame", artist: "David Bowie", ytId: "Ypgq0qdgVZA" },
    "1975-10": { title: "Bad Blood", artist: "Neil Sedaka", ytId: "vO7bE-k_iSE" },
    "1975-11": { title: "Island Girl", artist: "Elton John", ytId: "xpRZZmB9zB0" },
    "1975-12": { title: "That's the Way (I Like It)", artist: "KC and the Sunshine Band", ytId: "yupPvZF6oBw" },

    // ---- 1980 ----
    "1980-01": { title: "Please Don't Go", artist: "KC and the Sunshine Band", ytId: "CwBO0LPgfCo" },
    "1980-02": { title: "Do That to Me One More Time", artist: "Captain & Tennille", ytId: "KxJFOvqRIiA" },
    "1980-03": { title: "Crazy Little Thing Called Love", artist: "Queen", ytId: "zO6D_BAuYCI" },
    "1980-04": { title: "Call Me", artist: "Blondie", ytId: "StKVS0eI85I" },
    "1980-05": { title: "Call Me", artist: "Blondie", ytId: "StKVS0eI85I" },
    "1980-06": { title: "Funkytown", artist: "Lipps Inc.", ytId: "s36eQwgPNSE" },
    "1980-07": { title: "Coming Up", artist: "Paul McCartney", ytId: "TJ4ISME8atY" },
    "1980-08": { title: "Magic", artist: "Olivia Newton-John", ytId: "DZIJaGVGZAE" },
    "1980-09": { title: "Upside Down", artist: "Diana Ross", ytId: "PlIzKaGBeHk" },
    "1980-10": { title: "Another One Bites the Dust", artist: "Queen", ytId: "rY0WxgSXdEE" },
    "1980-11": { title: "Woman in Love", artist: "Barbra Streisand", ytId: "mK5E_BNQN6o" },
    "1980-12": { title: "(Just Like) Starting Over", artist: "John Lennon", ytId: "5XqPNMHRBRo" },

    // ---- 1985 ----
    "1985-01": { title: "Like a Virgin", artist: "Madonna", ytId: "s__rX_WL100" },
    "1985-02": { title: "Careless Whisper", artist: "Wham! ft. George Michael", ytId: "izGwDsrQ1eQ" },
    "1985-03": { title: "Can't Fight This Feeling", artist: "REO Speedwagon", ytId: "zpOULjyy-n8" },
    "1985-04": { title: "We Are the World", artist: "USA for Africa", ytId: "9AjkUyj0rVE" },
    "1985-05": { title: "Don't You (Forget About Me)", artist: "Simple Minds", ytId: "CdqoNKCCt7A" },
    "1985-06": { title: "Everybody Wants to Rule the World", artist: "Tears for Fears", ytId: "aGCdLKXNF3w" },
    "1985-07": { title: "A View to a Kill", artist: "Duran Duran", ytId: "jxulwL8bbXU" },
    "1985-08": { title: "Shout", artist: "Tears for Fears", ytId: "Ye7FKc1JQe4" },
    "1985-09": { title: "St. Elmo's Fire (Man in Motion)", artist: "John Parr", ytId: "EOvMpND3wes" },
    "1985-10": { title: "Take on Me", artist: "a-ha", ytId: "djV11Xbc914" },
    "1985-11": { title: "We Built This City", artist: "Starship", ytId: "K1b8AhIsSYQ" },
    "1985-12": { title: "Say You, Say Me", artist: "Lionel Richie", ytId: "ODMCngMfnKE" },

    // ---- 1990 ----
    "1990-01": { title: "Another Day in Paradise", artist: "Phil Collins", ytId: "Qt2mbGP6vFI" },
    "1990-02": { title: "Opposites Attract", artist: "Paula Abdul", ytId: "xweiQukBM_k" },
    "1990-03": { title: "Escapade", artist: "Janet Jackson", ytId: "VWePbVa6E3c" },
    "1990-04": { title: "Nothing Compares 2 U", artist: "Sinéad O'Connor", ytId: "0-EF60neguk" },
    "1990-05": { title: "Vogue", artist: "Madonna", ytId: "GuJQSAiODqI" },
    "1990-06": { title: "It Must Have Been Love", artist: "Roxette", ytId: "k2C5TjS2sh4" },
    "1990-07": { title: "She Ain't Worth It", artist: "Glenn Medeiros ft. Bobby Brown", ytId: "6BOTaKYuH44" },
    "1990-08": { title: "Vision of Love", artist: "Mariah Carey", ytId: "tov22NtfYlg" },
    "1990-09": { title: "Release Me", artist: "Wilson Phillips", ytId: "7PDG_HMX5ZE" },
    "1990-10": { title: "Praying for Time", artist: "George Michael", ytId: "UHy5FK9fE_w" },
    "1990-11": { title: "Love Takes Time", artist: "Mariah Carey", ytId: "EmpXFj9LDOU" },
    "1990-12": { title: "Because I Love You", artist: "Stevie B", ytId: "2ABVCxFszjA" },

    // ---- 1991 ----
    "1991-01": { title: "Justify My Love", artist: "Madonna", ytId: "Np_Y740aReI" },
    "1991-02": { title: "Gonna Make You Sweat", artist: "C+C Music Factory", ytId: "LaTGrV58wec" },
    "1991-03": { title: "Someday", artist: "Mariah Carey", ytId: "0LX45x-cclU" },
    "1991-04": { title: "I've Been Thinking About You", artist: "Londonbeat", ytId: "xnKT3mcNZnM" },
    "1991-05": { title: "Baby Baby", artist: "Amy Grant", ytId: "U-kLSsU8vVE" },
    "1991-06": { title: "More Than Words", artist: "Extreme", ytId: "UrIiLvg58SY" },
    "1991-07": { title: "Rush Rush", artist: "Paula Abdul", ytId: "WW3AeJhWvZ8" },
    "1991-08": { title: "(Everything I Do) I Do It for You", artist: "Bryan Adams", ytId: "ZGoWtY_h4xo" },
    "1991-09": { title: "The Promise of a New Day", artist: "Paula Abdul", ytId: "kBmPnL6DSRI" },
    "1991-10": { title: "Emotions", artist: "Mariah Carey", ytId: "NrJEFrth27Q" },
    "1991-11": { title: "Cream", artist: "Prince", ytId: "rrbFQEcpJ3A" },
    "1991-12": { title: "Black or White", artist: "Michael Jackson", ytId: "F2AitTPI5U0" },

    // ---- 1992 ----
    "1992-01": { title: "Black or White", artist: "Michael Jackson", ytId: "F2AitTPI5U0" },
    "1992-02": { title: "To Be with You", artist: "Mr. Big", ytId: "IaG0lti3vMs" },
    "1992-03": { title: "Save the Best for Last", artist: "Vanessa Williams", ytId: "5EdmHSTwmWY" },
    "1992-04": { title: "Save the Best for Last", artist: "Vanessa Williams", ytId: "5EdmHSTwmWY" },
    "1992-05": { title: "Jump", artist: "Kris Kross", ytId: "010KyIQjkTk" },
    "1992-06": { title: "I'll Be There", artist: "Mariah Carey", ytId: "VujnfEYycOk" },
    "1992-07": { title: "Baby Got Back", artist: "Sir Mix-a-Lot", ytId: "X53ZSxkQ3Ho" },
    "1992-08": { title: "Baby Got Back", artist: "Sir Mix-a-Lot", ytId: "X53ZSxkQ3Ho" },
    "1992-09": { title: "End of the Road", artist: "Boyz II Men", ytId: "zDKO6XYXioc" },
    "1992-10": { title: "End of the Road", artist: "Boyz II Men", ytId: "zDKO6XYXioc" },
    "1992-11": { title: "How Do You Talk to an Angel", artist: "The Heights", ytId: "2avJCjJ4bXs" },
    "1992-12": { title: "I Will Always Love You", artist: "Whitney Houston", ytId: "3JWTaaS7LdU" },

    // ---- 1993 ----
    "1993-01": { title: "I Will Always Love You", artist: "Whitney Houston", ytId: "3JWTaaS7LdU" },
    "1993-02": { title: "I Will Always Love You", artist: "Whitney Houston", ytId: "3JWTaaS7LdU" },
    "1993-03": { title: "Informer", artist: "Snow", ytId: "StlMdNcvCJo" },
    "1993-04": { title: "Freak Me", artist: "Silk", ytId: "4PZ0Py-6Y_Q" },
    "1993-05": { title: "That's the Way Love Goes", artist: "Janet Jackson", ytId: "6J2OlIpQgF8" },
    "1993-06": { title: "That's the Way Love Goes", artist: "Janet Jackson", ytId: "6J2OlIpQgF8" },
    "1993-07": { title: "Weak", artist: "SWV", ytId: "VbS9V_In2cM" },
    "1993-08": { title: "Can't Help Falling in Love", artist: "UB40", ytId: "N_hVBMbSHBg" },
    "1993-09": { title: "Dreamlover", artist: "Mariah Carey", ytId: "GCjNX3VuVZg" },
    "1993-10": { title: "Dreamlover", artist: "Mariah Carey", ytId: "GCjNX3VuVZg" },
    "1993-11": { title: "I'd Do Anything for Love", artist: "Meat Loaf", ytId: "9X_ViIPA-Gc" },
    "1993-12": { title: "Again", artist: "Janet Jackson", ytId: "Dv6liBLltiM" },

    // ---- 1994 ----
    "1994-01": { title: "Hero", artist: "Mariah Carey", ytId: "0IA3ZvCkRkQ" },
    "1994-02": { title: "The Power of Love", artist: "Céline Dion", ytId: "Y8HOfcYWZoo" },
    "1994-03": { title: "The Sign", artist: "Ace of Base", ytId: "iqu132vTl5Y" },
    "1994-04": { title: "Bump N' Grind", artist: "R. Kelly", ytId: "gTSzX7CjPTM" },
    "1994-05": { title: "I Swear", artist: "All-4-One", ytId: "25rL-ooWICU" },
    "1994-06": { title: "I Swear", artist: "All-4-One", ytId: "25rL-ooWICU" },
    "1994-07": { title: "I Swear", artist: "All-4-One", ytId: "25rL-ooWICU" },
    "1994-08": { title: "Stay (I Missed You)", artist: "Lisa Loeb & Nine Stories", ytId: "i9HGwRbMiVY" },
    "1994-09": { title: "I'll Make Love to You", artist: "Boyz II Men", ytId: "fV8vB1BB2qc" },
    "1994-10": { title: "I'll Make Love to You", artist: "Boyz II Men", ytId: "fV8vB1BB2qc" },
    "1994-11": { title: "I'll Make Love to You", artist: "Boyz II Men", ytId: "fV8vB1BB2qc" },
    "1994-12": { title: "On Bended Knee", artist: "Boyz II Men", ytId: "NBqjrR6Ef-0" },

    // ---- 1995 ----
    "1995-01": { title: "On Bended Knee", artist: "Boyz II Men", ytId: "NBqjrR6Ef-0" },
    "1995-02": { title: "Creep", artist: "TLC", ytId: "LlZydtG3xqI" },
    "1995-03": { title: "Take a Bow", artist: "Madonna", ytId: "XDOg3XoeEpA" },
    "1995-04": { title: "This Is How We Do It", artist: "Montell Jordan", ytId: "0hiUuL5uTKc" },
    "1995-05": { title: "This Is How We Do It", artist: "Montell Jordan", ytId: "0hiUuL5uTKc" },
    "1995-06": { title: "Waterfalls", artist: "TLC", ytId: "8WEtxJ4-sh4" },
    "1995-07": { title: "Waterfalls", artist: "TLC", ytId: "8WEtxJ4-sh4" },
    "1995-08": { title: "Kiss from a Rose", artist: "Seal", ytId: "AMD2TwRvuoU" },
    "1995-09": { title: "Gangsta's Paradise", artist: "Coolio ft. L.V.", ytId: "fPO76Jlnz6c" },
    "1995-10": { title: "Fantasy", artist: "Mariah Carey", ytId: "qq09UkPRdFY" },
    "1995-11": { title: "Exhale (Shoop Shoop)", artist: "Whitney Houston", ytId: "V-_x3ljcvaI" },
    "1995-12": { title: "One Sweet Day", artist: "Mariah Carey & Boyz II Men", ytId: "UXxRiGtkUJM" },

    // ---- 1996 ----
    "1996-01": { title: "One Sweet Day", artist: "Mariah Carey & Boyz II Men", ytId: "UXxRiGtkUJM" },
    "1996-02": { title: "One Sweet Day", artist: "Mariah Carey & Boyz II Men", ytId: "UXxRiGtkUJM" },
    "1996-03": { title: "Because You Loved Me", artist: "Céline Dion", ytId: "fpl4if07ics" },
    "1996-04": { title: "Because You Loved Me", artist: "Céline Dion", ytId: "fpl4if07ics" },
    "1996-05": { title: "Tha Crossroads", artist: "Bone Thugs-n-Harmony", ytId: "VMYAEHE2GrM" },
    "1996-06": { title: "Tha Crossroads", artist: "Bone Thugs-n-Harmony", ytId: "VMYAEHE2GrM" },
    "1996-07": { title: "You're Makin' Me High / Let It Flow", artist: "Toni Braxton", ytId: "b1CjSTqb_2M" },
    "1996-08": { title: "Macarena (Bayside Boys Mix)", artist: "Los Del Rio", ytId: "zWaymcVmJ-A" },
    "1996-09": { title: "Macarena (Bayside Boys Mix)", artist: "Los Del Rio", ytId: "zWaymcVmJ-A" },
    "1996-10": { title: "Macarena (Bayside Boys Mix)", artist: "Los Del Rio", ytId: "zWaymcVmJ-A" },
    "1996-11": { title: "No Diggity", artist: "Blackstreet ft. Dr. Dre", ytId: "3KL9mRus19o" },
    "1996-12": { title: "Un-Break My Heart", artist: "Toni Braxton", ytId: "p2Rch6WvPJE" },

    // ---- 1997 ----
    "1997-01": { title: "Un-Break My Heart", artist: "Toni Braxton", ytId: "p2Rch6WvPJE" },
    "1997-02": { title: "Wannabe", artist: "Spice Girls", ytId: "gJLIiF15wjQ" },
    "1997-03": { title: "MMMBop", artist: "Hanson", ytId: "NHozn0YXAeE" },
    "1997-04": { title: "Return of the Mack", artist: "Mark Morrison", ytId: "uB1D9wWxd2w" },
    "1997-05": { title: "MMMBop", artist: "Hanson", ytId: "NHozn0YXAeE" },
    "1997-06": { title: "I'll Be Missing You", artist: "Puff Daddy & Faith Evans ft. 112", ytId: "mM0-ZU8njdo" },
    "1997-07": { title: "I'll Be Missing You", artist: "Puff Daddy & Faith Evans ft. 112", ytId: "mM0-ZU8njdo" },
    "1997-08": { title: "Mo Money Mo Problems", artist: "The Notorious B.I.G.", ytId: "gUhRKVL1fhM" },
    "1997-09": { title: "Honey", artist: "Mariah Carey", ytId: "w3KOowB4k_k" },
    "1997-10": { title: "Candle in the Wind 1997", artist: "Elton John", ytId: "RbhcREeSRag" },
    "1997-11": { title: "Candle in the Wind 1997", artist: "Elton John", ytId: "RbhcREeSRag" },
    "1997-12": { title: "Candle in the Wind 1997", artist: "Elton John", ytId: "RbhcREeSRag" },

    // ---- 1998 ----
    "1998-01": { title: "Together Again", artist: "Janet Jackson", ytId: "GfCqMv--0NA" },
    "1998-02": { title: "Nice & Slow", artist: "Usher", ytId: "MfCJMfBmVFw" },
    "1998-03": { title: "Gettin' Jiggy wit It", artist: "Will Smith", ytId: "3JcmQONgXJM" },
    "1998-04": { title: "Too Close", artist: "Next", ytId: "kwse08s4gpc" },
    "1998-05": { title: "Too Close", artist: "Next", ytId: "kwse08s4gpc" },
    "1998-06": { title: "The Boy Is Mine", artist: "Brandy & Monica", ytId: "Va1Y6uAgNQA" },
    "1998-07": { title: "The Boy Is Mine", artist: "Brandy & Monica", ytId: "Va1Y6uAgNQA" },
    "1998-08": { title: "The Boy Is Mine", artist: "Brandy & Monica", ytId: "Va1Y6uAgNQA" },
    "1998-09": { title: "I Don't Want to Miss a Thing", artist: "Aerosmith", ytId: "JkK8g6FMEXE" },
    "1998-10": { title: "The First Night", artist: "Monica", ytId: "AslLGjRYaBk" },
    "1998-11": { title: "Doo Wop (That Thing)", artist: "Lauryn Hill", ytId: "T6QKqFPRByw" },
    "1998-12": { title: "I'm Your Angel", artist: "R. Kelly & Céline Dion", ytId: "HfzS5KRjh-Q" },

    // ---- 1999 ----
    "1999-01": { title: "...Baby One More Time", artist: "Britney Spears", ytId: "C-u5WLJ9Yk4" },
    "1999-02": { title: "Angel of Mine", artist: "Monica", ytId: "FtsBy7_ISzE" },
    "1999-03": { title: "Believe", artist: "Cher", ytId: "nZXRV4MsEfc" },
    "1999-04": { title: "No Scrubs", artist: "TLC", ytId: "FrLequ6dUdM" },
    "1999-05": { title: "Livin' la Vida Loca", artist: "Ricky Martin", ytId: "p47fEXGabaY" },
    "1999-06": { title: "If You Had My Love", artist: "Jennifer Lopez", ytId: "lYfkl-HXqQQ" },
    "1999-07": { title: "Genie in a Bottle", artist: "Christina Aguilera", ytId: "kIDWgqDBNXA" },
    "1999-08": { title: "Genie in a Bottle", artist: "Christina Aguilera", ytId: "kIDWgqDBNXA" },
    "1999-09": { title: "Unpretty", artist: "TLC", ytId: "g2gy1Evb1Kg" },
    "1999-10": { title: "Smooth", artist: "Santana ft. Rob Thomas", ytId: "6Whgn_gE9wI" },
    "1999-11": { title: "Smooth", artist: "Santana ft. Rob Thomas", ytId: "6Whgn_gE9wI" },
    "1999-12": { title: "Smooth", artist: "Santana ft. Rob Thomas", ytId: "6Whgn_gE9wI" },

    // ---- 2000 ----
    "2000-01": { title: "Smooth", artist: "Santana ft. Rob Thomas", ytId: "6Whgn_gE9wI" },
    "2000-02": { title: "I Knew I Loved You", artist: "Savage Garden", ytId: "jjnmICxvoVY" },
    "2000-03": { title: "Say My Name", artist: "Destiny's Child", ytId: "sQgd6MccwDg" },
    "2000-04": { title: "Maria Maria", artist: "Santana ft. The Product G&B", ytId: "nPLV7lGKzHY" },
    "2000-05": { title: "Maria Maria", artist: "Santana ft. The Product G&B", ytId: "nPLV7lGKzHY" },
    "2000-06": { title: "Be with You", artist: "Enrique Iglesias", ytId: "MnkeKsnfIcI" },
    "2000-07": { title: "It's Gonna Be Me", artist: "*NSYNC", ytId: "GQMlWwIXg3M" },
    "2000-08": { title: "Doesn't Really Matter", artist: "Janet Jackson", ytId: "-IVJKZfBkNg" },
    "2000-09": { title: "Music", artist: "Madonna", ytId: "SCWscYn18mU" },
    "2000-10": { title: "Come On Over Baby", artist: "Christina Aguilera", ytId: "6M52dXWJaAk" },
    "2000-11": { title: "Independent Women Part I", artist: "Destiny's Child", ytId: "0lPQZni7I18" },
    "2000-12": { title: "Independent Women Part I", artist: "Destiny's Child", ytId: "0lPQZni7I18" },

    // ---- 2001 ----
    "2001-01": { title: "Independent Women Part I", artist: "Destiny's Child", ytId: "0lPQZni7I18" },
    "2001-02": { title: "It Wasn't Me", artist: "Shaggy ft. RikRok", ytId: "Qv5fqunQ_4I" },
    "2001-03": { title: "Angel", artist: "Shaggy ft. Rayvon", ytId: "XWJrPzAUzAs" },
    "2001-04": { title: "All for You", artist: "Janet Jackson", ytId: "YgiEiLuJj-Y" },
    "2001-05": { title: "All for You", artist: "Janet Jackson", ytId: "YgiEiLuJj-Y" },
    "2001-06": { title: "Lady Marmalade", artist: "Christina, Lil' Kim, Mya, Pink", ytId: "RQa7SvVCdZk" },
    "2001-07": { title: "Bootylicious", artist: "Destiny's Child", ytId: "IyYnnUcgeMc" },
    "2001-08": { title: "Fallin'", artist: "Alicia Keys", ytId: "Urdlvw0KNEE" },
    "2001-09": { title: "Fallin'", artist: "Alicia Keys", ytId: "Urdlvw0KNEE" },
    "2001-10": { title: "I'm Real", artist: "Jennifer Lopez ft. Ja Rule", ytId: "JTkl6wkfSbw" },
    "2001-11": { title: "Family Affair", artist: "Mary J. Blige", ytId: "znlFu_lemsU" },
    "2001-12": { title: "How You Remind Me", artist: "Nickelback", ytId: "1cQh1ccqu8M" },

    // ---- 2002 ----
    "2002-01": { title: "How You Remind Me", artist: "Nickelback", ytId: "1cQh1ccqu8M" },
    "2002-02": { title: "Always on Time", artist: "Ja Rule ft. Ashanti", ytId: "0tcDXJfAFVw" },
    "2002-03": { title: "Ain't It Funny", artist: "Jennifer Lopez ft. Ja Rule", ytId: "GwjelfbGiQ8" },
    "2002-04": { title: "Foolish", artist: "Ashanti", ytId: "TjuZkXSvABM" },
    "2002-05": { title: "Foolish", artist: "Ashanti", ytId: "TjuZkXSvABM" },
    "2002-06": { title: "Hot in Herre", artist: "Nelly", ytId: "GeZZr_p6vB8" },
    "2002-07": { title: "Hot in Herre", artist: "Nelly", ytId: "GeZZr_p6vB8" },
    "2002-08": { title: "Dilemma", artist: "Nelly ft. Kelly Rowland", ytId: "8WYHDfJDPDc" },
    "2002-09": { title: "Dilemma", artist: "Nelly ft. Kelly Rowland", ytId: "8WYHDfJDPDc" },
    "2002-10": { title: "Dilemma", artist: "Nelly ft. Kelly Rowland", ytId: "8WYHDfJDPDc" },
    "2002-11": { title: "Lose Yourself", artist: "Eminem", ytId: "_Yhyp-_hX2s" },
    "2002-12": { title: "Lose Yourself", artist: "Eminem", ytId: "_Yhyp-_hX2s" },

    // ---- 2003 ----
    "2003-01": { title: "Lose Yourself", artist: "Eminem", ytId: "_Yhyp-_hX2s" },
    "2003-02": { title: "All I Have", artist: "Jennifer Lopez ft. LL Cool J", ytId: "JlLjb-nRaJs" },
    "2003-03": { title: "In Da Club", artist: "50 Cent", ytId: "5qm8PH4xAss" },
    "2003-04": { title: "In Da Club", artist: "50 Cent", ytId: "5qm8PH4xAss" },
    "2003-05": { title: "Get Busy", artist: "Sean Paul", ytId: "OcaPu9JPenU" },
    "2003-06": { title: "21 Questions", artist: "50 Cent ft. Nate Dogg", ytId: "cDMhlvbOFaM" },
    "2003-07": { title: "Crazy in Love", artist: "Beyoncé ft. Jay-Z", ytId: "ViwtNLUqkMY" },
    "2003-08": { title: "Crazy in Love", artist: "Beyoncé ft. Jay-Z", ytId: "ViwtNLUqkMY" },
    "2003-09": { title: "Shake Ya Tailfeather", artist: "Nelly, P. Diddy & Murphy Lee", ytId: "vj3qCCMk1Ow" },
    "2003-10": { title: "Baby Boy", artist: "Beyoncé ft. Sean Paul", ytId: "8ucz_pm3LX8" },
    "2003-11": { title: "Stand Up", artist: "Ludacris ft. Shawnna", ytId: "RtSDWq6HsJE" },
    "2003-12": { title: "Hey Ya!", artist: "OutKast", ytId: "PWgvGjAhvIw" },

    // ---- 2004 ----
    "2004-01": { title: "Hey Ya!", artist: "OutKast", ytId: "PWgvGjAhvIw" },
    "2004-02": { title: "Yeah!", artist: "Usher ft. Lil Jon & Ludacris", ytId: "GxBSyx85Kp8" },
    "2004-03": { title: "Yeah!", artist: "Usher ft. Lil Jon & Ludacris", ytId: "GxBSyx85Kp8" },
    "2004-04": { title: "Yeah!", artist: "Usher ft. Lil Jon & Ludacris", ytId: "GxBSyx85Kp8" },
    "2004-05": { title: "Burn", artist: "Usher", ytId: "t5XNWFw5HVw" },
    "2004-06": { title: "Burn", artist: "Usher", ytId: "t5XNWFw5HVw" },
    "2004-07": { title: "Confessions Part II", artist: "Usher", ytId: "5Ty8TfB7hLQ" },
    "2004-08": { title: "Lean Back", artist: "Terror Squad", ytId: "ajmI1P3r1w4" },
    "2004-09": { title: "Goodies", artist: "Ciara ft. Petey Pablo", ytId: "YJQhCLNm11A" },
    "2004-10": { title: "Goodies", artist: "Ciara ft. Petey Pablo", ytId: "YJQhCLNm11A" },
    "2004-11": { title: "My Boo", artist: "Usher & Alicia Keys", ytId: "LJXbkvLxil0" },
    "2004-12": { title: "Drop It Like It's Hot", artist: "Snoop Dogg ft. Pharrell", ytId: "GtUVQei3nX4" },

    // ---- 2005 ----
    "2005-01": { title: "Let Me Love You", artist: "Mario", ytId: "H64QG4UsrGo" },
    "2005-02": { title: "Let Me Love You", artist: "Mario", ytId: "H64QG4UsrGo" },
    "2005-03": { title: "Candy Shop", artist: "50 Cent ft. Olivia", ytId: "SRcnnId15BA" },
    "2005-04": { title: "Candy Shop", artist: "50 Cent ft. Olivia", ytId: "SRcnnId15BA" },
    "2005-05": { title: "Hollaback Girl", artist: "Gwen Stefani", ytId: "Kgjkth6BRRY" },
    "2005-06": { title: "We Belong Together", artist: "Mariah Carey", ytId: "0habxsuXW4g" },
    "2005-07": { title: "We Belong Together", artist: "Mariah Carey", ytId: "0habxsuXW4g" },
    "2005-08": { title: "We Belong Together", artist: "Mariah Carey", ytId: "0habxsuXW4g" },
    "2005-09": { title: "Gold Digger", artist: "Kanye West ft. Jamie Foxx", ytId: "6vwNcNOTVzY" },
    "2005-10": { title: "Gold Digger", artist: "Kanye West ft. Jamie Foxx", ytId: "6vwNcNOTVzY" },
    "2005-11": { title: "Gold Digger", artist: "Kanye West ft. Jamie Foxx", ytId: "6vwNcNOTVzY" },
    "2005-12": { title: "Don't Forget About Us", artist: "Mariah Carey", ytId: "57gcZXf6oto" },

    // ---- 2010 ----
    "2010-01": { title: "TiK ToK", artist: "Kesha", ytId: "iP6XpLQM2Cs" },
    "2010-02": { title: "TiK ToK", artist: "Kesha", ytId: "iP6XpLQM2Cs" },
    "2010-03": { title: "Imma Be", artist: "The Black Eyed Peas", ytId: "kdAj-dBNCi4" },
    "2010-04": { title: "Rude Boy", artist: "Rihanna", ytId: "e82VE8UtW8A" },
    "2010-05": { title: "Nothin' on You", artist: "B.o.B ft. Bruno Mars", ytId: "8PTDv_szmL0" },
    "2010-06": { title: "OMG", artist: "Usher ft. will.i.am", ytId: "1RnPB76mjxI" },
    "2010-07": { title: "California Gurls", artist: "Katy Perry ft. Snoop Dogg", ytId: "F57P9C4SAW4" },
    "2010-08": { title: "Love the Way You Lie", artist: "Eminem ft. Rihanna", ytId: "uelHwf8o7_U" },
    "2010-09": { title: "Love the Way You Lie", artist: "Eminem ft. Rihanna", ytId: "uelHwf8o7_U" },
    "2010-10": { title: "Just the Way You Are", artist: "Bruno Mars", ytId: "LjhCEhWiKXk" },
    "2010-11": { title: "We R Who We R", artist: "Kesha", ytId: "mXvmSh40FhI" },
    "2010-12": { title: "Firework", artist: "Katy Perry", ytId: "QGJuMBdaqIw" },

    // ---- 2015 ----
    "2015-01": { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", ytId: "OPf0YbXqDm0" },
    "2015-02": { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", ytId: "OPf0YbXqDm0" },
    "2015-03": { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", ytId: "OPf0YbXqDm0" },
    "2015-04": { title: "See You Again", artist: "Wiz Khalifa ft. Charlie Puth", ytId: "RgKAFK5djSk" },
    "2015-05": { title: "See You Again", artist: "Wiz Khalifa ft. Charlie Puth", ytId: "RgKAFK5djSk" },
    "2015-06": { title: "Bad Blood", artist: "Taylor Swift ft. Kendrick Lamar", ytId: "QcIy9NiNbmo" },
    "2015-07": { title: "Cheerleader", artist: "OMI", ytId: "jGflUbPQfos" },
    "2015-08": { title: "Can't Feel My Face", artist: "The Weeknd", ytId: "KEI4qSrkPAs" },
    "2015-09": { title: "The Hills", artist: "The Weeknd", ytId: "yzTuBuRdAyA" },
    "2015-10": { title: "What Do You Mean?", artist: "Justin Bieber", ytId: "DK_0jXPuIr0" },
    "2015-11": { title: "Hello", artist: "Adele", ytId: "YQHsXMglC9A" },
    "2015-12": { title: "Hello", artist: "Adele", ytId: "YQHsXMglC9A" },

    // ---- 2016 ----
    "2016-01": { title: "Sorry", artist: "Justin Bieber", ytId: "fRh_vgS2dFE" },
    "2016-02": { title: "Love Yourself", artist: "Justin Bieber", ytId: "oyEuk8j8imI" },
    "2016-03": { title: "Love Yourself", artist: "Justin Bieber", ytId: "oyEuk8j8imI" },
    "2016-04": { title: "Work", artist: "Rihanna ft. Drake", ytId: "HL1UzIK-flA" },
    "2016-05": { title: "Panda", artist: "Desiigner", ytId: "E5ONTXHS2mM" },
    "2016-06": { title: "One Dance", artist: "Drake ft. WizKid & Kyla", ytId: "qL3wD1CLZJ0" },
    "2016-07": { title: "One Dance", artist: "Drake ft. WizKid & Kyla", ytId: "qL3wD1CLZJ0" },
    "2016-08": { title: "Cheap Thrills", artist: "Sia ft. Sean Paul", ytId: "nYh-n7EOtMA" },
    "2016-09": { title: "Closer", artist: "The Chainsmokers ft. Halsey", ytId: "PT2_F-1esPk" },
    "2016-10": { title: "Closer", artist: "The Chainsmokers ft. Halsey", ytId: "PT2_F-1esPk" },
    "2016-11": { title: "Starboy", artist: "The Weeknd ft. Daft Punk", ytId: "34Na4j8AVgA" },
    "2016-12": { title: "Black Beatles", artist: "Rae Sremmurd ft. Gucci Mane", ytId: "b8m9zhNAgKs" },

    // ---- 2017 ----
    "2017-01": { title: "Starboy", artist: "The Weeknd ft. Daft Punk", ytId: "34Na4j8AVgA" },
    "2017-02": { title: "Shape of You", artist: "Ed Sheeran", ytId: "JGwWNGJdvx8" },
    "2017-03": { title: "Shape of You", artist: "Ed Sheeran", ytId: "JGwWNGJdvx8" },
    "2017-04": { title: "Shape of You", artist: "Ed Sheeran", ytId: "JGwWNGJdvx8" },
    "2017-05": { title: "That's What I Like", artist: "Bruno Mars", ytId: "PMivT7MJ41M" },
    "2017-06": { title: "Despacito", artist: "Luis Fonsi & Daddy Yankee ft. Justin Bieber", ytId: "kJQP7kiw5Fk" },
    "2017-07": { title: "Despacito", artist: "Luis Fonsi & Daddy Yankee ft. Justin Bieber", ytId: "kJQP7kiw5Fk" },
    "2017-08": { title: "Despacito", artist: "Luis Fonsi & Daddy Yankee ft. Justin Bieber", ytId: "kJQP7kiw5Fk" },
    "2017-09": { title: "Look What You Made Me Do", artist: "Taylor Swift", ytId: "3tmd-ClpJxA" },
    "2017-10": { title: "Rockstar", artist: "Post Malone ft. 21 Savage", ytId: "UceaB4D0jpo" },
    "2017-11": { title: "Rockstar", artist: "Post Malone ft. 21 Savage", ytId: "UceaB4D0jpo" },
    "2017-12": { title: "Rockstar", artist: "Post Malone ft. 21 Savage", ytId: "UceaB4D0jpo" },

    // ---- 2018 ----
    "2018-01": { title: "Perfect", artist: "Ed Sheeran", ytId: "2Vv-BfVoq4g" },
    "2018-02": { title: "God's Plan", artist: "Drake", ytId: "xpVfcZ0ZcFM" },
    "2018-03": { title: "God's Plan", artist: "Drake", ytId: "xpVfcZ0ZcFM" },
    "2018-04": { title: "God's Plan", artist: "Drake", ytId: "xpVfcZ0ZcFM" },
    "2018-05": { title: "Nice for What", artist: "Drake", ytId: "U9BwWKXjVaI" },
    "2018-06": { title: "Nice for What", artist: "Drake", ytId: "U9BwWKXjVaI" },
    "2018-07": { title: "I Like It", artist: "Cardi B, Bad Bunny & J Balvin", ytId: "xTlNMmZKwpA" },
    "2018-08": { title: "In My Feelings", artist: "Drake", ytId: "DRS_PpOrUZ4" },
    "2018-09": { title: "In My Feelings", artist: "Drake", ytId: "DRS_PpOrUZ4" },
    "2018-10": { title: "Girls Like You", artist: "Maroon 5 ft. Cardi B", ytId: "aJOTlE1K90k" },
    "2018-11": { title: "Girls Like You", artist: "Maroon 5 ft. Cardi B", ytId: "aJOTlE1K90k" },
    "2018-12": { title: "Thank U, Next", artist: "Ariana Grande", ytId: "gl1aHhXnN1k" },

    // ---- 2019 ----
    "2019-01": { title: "Thank U, Next", artist: "Ariana Grande", ytId: "gl1aHhXnN1k" },
    "2019-02": { title: "7 Rings", artist: "Ariana Grande", ytId: "QYh6mYIJG2Y" },
    "2019-03": { title: "7 Rings", artist: "Ariana Grande", ytId: "QYh6mYIJG2Y" },
    "2019-04": { title: "Old Town Road", artist: "Lil Nas X ft. Billy Ray Cyrus", ytId: "w2Ov5jzm3j8" },
    "2019-05": { title: "Old Town Road", artist: "Lil Nas X ft. Billy Ray Cyrus", ytId: "w2Ov5jzm3j8" },
    "2019-06": { title: "Old Town Road", artist: "Lil Nas X ft. Billy Ray Cyrus", ytId: "w2Ov5jzm3j8" },
    "2019-07": { title: "Old Town Road", artist: "Lil Nas X ft. Billy Ray Cyrus", ytId: "w2Ov5jzm3j8" },
    "2019-08": { title: "Old Town Road", artist: "Lil Nas X ft. Billy Ray Cyrus", ytId: "w2Ov5jzm3j8" },
    "2019-09": { title: "Truth Hurts", artist: "Lizzo", ytId: "P00HMxdsVZI" },
    "2019-10": { title: "Someone You Loved", artist: "Lewis Capaldi", ytId: "bCuhuePlP8o" },
    "2019-11": { title: "Someone You Loved", artist: "Lewis Capaldi", ytId: "bCuhuePlP8o" },
    "2019-12": { title: "All I Want for Christmas Is You", artist: "Mariah Carey", ytId: "aAkMkVFwAoo" },

    // ---- 2020 ----
    "2020-01": { title: "All I Want for Christmas Is You", artist: "Mariah Carey", ytId: "aAkMkVFwAoo" },
    "2020-02": { title: "The Box", artist: "Roddy Ricch", ytId: "uLHqnDG7HYo" },
    "2020-03": { title: "The Box", artist: "Roddy Ricch", ytId: "uLHqnDG7HYo" },
    "2020-04": { title: "Blinding Lights", artist: "The Weeknd", ytId: "4NRXx6U8ABQ" },
    "2020-05": { title: "Blinding Lights", artist: "The Weeknd", ytId: "4NRXx6U8ABQ" },
    "2020-06": { title: "Rockstar", artist: "DaBaby ft. Roddy Ricch", ytId: "mxFstYSbBmc" },
    "2020-07": { title: "Rockstar", artist: "DaBaby ft. Roddy Ricch", ytId: "mxFstYSbBmc" },
    "2020-08": { title: "WAP", artist: "Cardi B ft. Megan Thee Stallion", ytId: "hsm4poTWjMs" },
    "2020-09": { title: "WAP", artist: "Cardi B ft. Megan Thee Stallion", ytId: "hsm4poTWjMs" },
    "2020-10": { title: "Savage Love", artist: "Jawsh 685 & Jason Derulo", ytId: "gUci-tsiU4I" },
    "2020-11": { title: "Positions", artist: "Ariana Grande", ytId: "tcYodQoapMg" },
    "2020-12": { title: "All I Want for Christmas Is You", artist: "Mariah Carey", ytId: "aAkMkVFwAoo" },

    // ---- 2021 ----
    "2021-01": { title: "Drivers License", artist: "Olivia Rodrigo", ytId: "ZmDBbnmKpqQ" },
    "2021-02": { title: "Drivers License", artist: "Olivia Rodrigo", ytId: "ZmDBbnmKpqQ" },
    "2021-03": { title: "Up", artist: "Cardi B", ytId: "rCiBgLOcuKU" },
    "2021-04": { title: "Montero (Call Me by Your Name)", artist: "Lil Nas X", ytId: "6swmTBVI83k" },
    "2021-05": { title: "Peaches", artist: "Justin Bieber ft. Daniel Caesar & Giveon", ytId: "tQ0yjYUFKAE" },
    "2021-06": { title: "Butter", artist: "BTS", ytId: "WMweEpGlu_U" },
    "2021-07": { title: "Permission to Dance", artist: "BTS", ytId: "CuklIb9d3fI" },
    "2021-08": { title: "Stay", artist: "The Kid LAROI & Justin Bieber", ytId: "kTJczUoc26U" },
    "2021-09": { title: "Industry Baby", artist: "Lil Nas X & Jack Harlow", ytId: "UTHLKHL_whs" },
    "2021-10": { title: "Easy on Me", artist: "Adele", ytId: "U3ASj1L6_sY" },
    "2021-11": { title: "Easy on Me", artist: "Adele", ytId: "U3ASj1L6_sY" },
    "2021-12": { title: "All I Want for Christmas Is You", artist: "Mariah Carey", ytId: "aAkMkVFwAoo" },

    // ---- 2022 ----
    "2022-01": { title: "Easy on Me", artist: "Adele", ytId: "U3ASj1L6_sY" },
    "2022-02": { title: "Heat Waves", artist: "Glass Animals", ytId: "mRD0-GxKHVo" },
    "2022-03": { title: "Heat Waves", artist: "Glass Animals", ytId: "mRD0-GxKHVo" },
    "2022-04": { title: "As It Was", artist: "Harry Styles", ytId: "H5v3kku4y6Q" },
    "2022-05": { title: "As It Was", artist: "Harry Styles", ytId: "H5v3kku4y6Q" },
    "2022-06": { title: "As It Was", artist: "Harry Styles", ytId: "H5v3kku4y6Q" },
    "2022-07": { title: "As It Was", artist: "Harry Styles", ytId: "H5v3kku4y6Q" },
    "2022-08": { title: "About Damn Time", artist: "Lizzo", ytId: "58Qc1SUfqKY" },
    "2022-09": { title: "As It Was", artist: "Harry Styles", ytId: "H5v3kku4y6Q" },
    "2022-10": { title: "Unholy", artist: "Sam Smith & Kim Petras", ytId: "Uq9gPaIzbe8" },
    "2022-11": { title: "Anti-Hero", artist: "Taylor Swift", ytId: "b1kbLwvqugk" },
    "2022-12": { title: "All I Want for Christmas Is You", artist: "Mariah Carey", ytId: "aAkMkVFwAoo" },

    // ---- 2023 ----
    "2023-01": { title: "Flowers", artist: "Miley Cyrus", ytId: "G7KNmW9a75Y" },
    "2023-02": { title: "Flowers", artist: "Miley Cyrus", ytId: "G7KNmW9a75Y" },
    "2023-03": { title: "Flowers", artist: "Miley Cyrus", ytId: "G7KNmW9a75Y" },
    "2023-04": { title: "Last Night", artist: "Morgan Wallen", ytId: "r7GDKeMeDqE" },
    "2023-05": { title: "Last Night", artist: "Morgan Wallen", ytId: "r7GDKeMeDqE" },
    "2023-06": { title: "Last Night", artist: "Morgan Wallen", ytId: "r7GDKeMeDqE" },
    "2023-07": { title: "Last Night", artist: "Morgan Wallen", ytId: "r7GDKeMeDqE" },
    "2023-08": { title: "Vampire", artist: "Olivia Rodrigo", ytId: "RlPNh_PBZb4" },
    "2023-09": { title: "Paint the Town Red", artist: "Doja Cat", ytId: "gA2IazON-MU" },
    "2023-10": { title: "Paint the Town Red", artist: "Doja Cat", ytId: "gA2IazON-MU" },
    "2023-11": { title: "Cruel Summer", artist: "Taylor Swift", ytId: "ic8j13piAhQ" },
    "2023-12": { title: "All I Want for Christmas Is You", artist: "Mariah Carey", ytId: "aAkMkVFwAoo" },

    // ---- 2024 ----
    "2024-01": { title: "Lovin on Me", artist: "Jack Harlow", ytId: "KO3l6qNA2Q4" },
    "2024-02": { title: "Texas Hold 'Em", artist: "Beyoncé", ytId: "smEQjuzjyFo" },
    "2024-03": { title: "Texas Hold 'Em", artist: "Beyoncé", ytId: "smEQjuzjyFo" },
    "2024-04": { title: "We Can't Be Friends", artist: "Ariana Grande", ytId: "AIpvEPU2jKI" },
    "2024-05": { title: "Not Like Us", artist: "Kendrick Lamar", ytId: "T6eK-2OQtew" },
    "2024-06": { title: "Not Like Us", artist: "Kendrick Lamar", ytId: "T6eK-2OQtew" },
    "2024-07": { title: "A Bar Song (Tipsy)", artist: "Shaboozey", ytId: "uCBElQaSV9U" },
    "2024-08": { title: "A Bar Song (Tipsy)", artist: "Shaboozey", ytId: "uCBElQaSV9U" },
    "2024-09": { title: "A Bar Song (Tipsy)", artist: "Shaboozey", ytId: "uCBElQaSV9U" },
    "2024-10": { title: "Espresso", artist: "Sabrina Carpenter", ytId: "eVli-tstM5E" },
    "2024-11": { title: "Die with a Smile", artist: "Lady Gaga & Bruno Mars", ytId: "kn3z2IfQDFc" },
    "2024-12": { title: "All I Want for Christmas Is You", artist: "Mariah Carey", ytId: "aAkMkVFwAoo" }
  }
};
